[libraries]
commons-lang = "org.apache.commons:commons-lang3:3.12.0"
slf4j-api = "org.slf4j:slf4j-api:1.7.36"
slf4j-simple = "org.slf4j:slf4j-simple:1.7.36"
junit-api = "org.junit.jupiter:junit-jupiter-api:5.9.0"
junit-engine = "org.junit.jupiter:junit-jupiter-engine:5.9.0"
assertj-core = "org.assertj:assertj-core:3.23.1"